#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HELADERIA_CA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Heladeria_CA")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbl_DetalleFactura(Tbl_DetalleFactura instance);
    partial void UpdateTbl_DetalleFactura(Tbl_DetalleFactura instance);
    partial void DeleteTbl_DetalleFactura(Tbl_DetalleFactura instance);
    partial void InsertTbl_factura(Tbl_factura instance);
    partial void UpdateTbl_factura(Tbl_factura instance);
    partial void DeleteTbl_factura(Tbl_factura instance);
    partial void InsertTbl_producto(Tbl_producto instance);
    partial void UpdateTbl_producto(Tbl_producto instance);
    partial void DeleteTbl_producto(Tbl_producto instance);
    partial void InsertTbl_rol(Tbl_rol instance);
    partial void UpdateTbl_rol(Tbl_rol instance);
    partial void DeleteTbl_rol(Tbl_rol instance);
    partial void InsertTbl_sabor(Tbl_sabor instance);
    partial void UpdateTbl_sabor(Tbl_sabor instance);
    partial void DeleteTbl_sabor(Tbl_sabor instance);
    partial void InsertTbl_tipo_pago(Tbl_tipo_pago instance);
    partial void UpdateTbl_tipo_pago(Tbl_tipo_pago instance);
    partial void DeleteTbl_tipo_pago(Tbl_tipo_pago instance);
    partial void InsertTbl_usuario(Tbl_usuario instance);
    partial void UpdateTbl_usuario(Tbl_usuario instance);
    partial void DeleteTbl_usuario(Tbl_usuario instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::HELADERIA_CA.Properties.Settings.Default.Heladeria_CAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_DetalleFactura> Tbl_DetalleFactura
		{
			get
			{
				return this.GetTable<Tbl_DetalleFactura>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_factura> Tbl_factura
		{
			get
			{
				return this.GetTable<Tbl_factura>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_producto> Tbl_producto
		{
			get
			{
				return this.GetTable<Tbl_producto>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_rol> Tbl_rol
		{
			get
			{
				return this.GetTable<Tbl_rol>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_sabor> Tbl_sabor
		{
			get
			{
				return this.GetTable<Tbl_sabor>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_tipo_pago> Tbl_tipo_pago
		{
			get
			{
				return this.GetTable<Tbl_tipo_pago>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_usuario> Tbl_usuario
		{
			get
			{
				return this.GetTable<Tbl_usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_DetalleFactura")]
	public partial class Tbl_DetalleFactura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _detalle_id;
		
		private int _factura_id;
		
		private int _prod_id;
		
		private int _cantidad;
		
		private double _prod_precio;
		
		private EntityRef<Tbl_factura> _Tbl_factura;
		
		private EntityRef<Tbl_producto> _Tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondetalle_idChanging(int value);
    partial void Ondetalle_idChanged();
    partial void Onfactura_idChanging(int value);
    partial void Onfactura_idChanged();
    partial void Onprod_idChanging(int value);
    partial void Onprod_idChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void Onprod_precioChanging(double value);
    partial void Onprod_precioChanged();
    #endregion
		
		public Tbl_DetalleFactura()
		{
			this._Tbl_factura = default(EntityRef<Tbl_factura>);
			this._Tbl_producto = default(EntityRef<Tbl_producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detalle_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int detalle_id
		{
			get
			{
				return this._detalle_id;
			}
			set
			{
				if ((this._detalle_id != value))
				{
					this.Ondetalle_idChanging(value);
					this.SendPropertyChanging();
					this._detalle_id = value;
					this.SendPropertyChanged("detalle_id");
					this.Ondetalle_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factura_id", DbType="Int NOT NULL")]
		public int factura_id
		{
			get
			{
				return this._factura_id;
			}
			set
			{
				if ((this._factura_id != value))
				{
					if (this._Tbl_factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfactura_idChanging(value);
					this.SendPropertyChanging();
					this._factura_id = value;
					this.SendPropertyChanged("factura_id");
					this.Onfactura_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_id", DbType="Int NOT NULL")]
		public int prod_id
		{
			get
			{
				return this._prod_id;
			}
			set
			{
				if ((this._prod_id != value))
				{
					if (this._Tbl_producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprod_idChanging(value);
					this.SendPropertyChanging();
					this._prod_id = value;
					this.SendPropertyChanged("prod_id");
					this.Onprod_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_precio", DbType="Float NOT NULL")]
		public double prod_precio
		{
			get
			{
				return this._prod_precio;
			}
			set
			{
				if ((this._prod_precio != value))
				{
					this.Onprod_precioChanging(value);
					this.SendPropertyChanging();
					this._prod_precio = value;
					this.SendPropertyChanged("prod_precio");
					this.Onprod_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_factura_Tbl_DetalleFactura", Storage="_Tbl_factura", ThisKey="factura_id", OtherKey="factura_id", IsForeignKey=true)]
		public Tbl_factura Tbl_factura
		{
			get
			{
				return this._Tbl_factura.Entity;
			}
			set
			{
				Tbl_factura previousValue = this._Tbl_factura.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_factura.Entity = null;
						previousValue.Tbl_DetalleFactura.Remove(this);
					}
					this._Tbl_factura.Entity = value;
					if ((value != null))
					{
						value.Tbl_DetalleFactura.Add(this);
						this._factura_id = value.factura_id;
					}
					else
					{
						this._factura_id = default(int);
					}
					this.SendPropertyChanged("Tbl_factura");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_producto_Tbl_DetalleFactura", Storage="_Tbl_producto", ThisKey="prod_id", OtherKey="prod_id", IsForeignKey=true)]
		public Tbl_producto Tbl_producto
		{
			get
			{
				return this._Tbl_producto.Entity;
			}
			set
			{
				Tbl_producto previousValue = this._Tbl_producto.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_producto.Entity = null;
						previousValue.Tbl_DetalleFactura.Remove(this);
					}
					this._Tbl_producto.Entity = value;
					if ((value != null))
					{
						value.Tbl_DetalleFactura.Add(this);
						this._prod_id = value.prod_id;
					}
					else
					{
						this._prod_id = default(int);
					}
					this.SendPropertyChanged("Tbl_producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_factura")]
	public partial class Tbl_factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _factura_id;
		
		private EntitySet<Tbl_DetalleFactura> _Tbl_DetalleFactura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfactura_idChanging(int value);
    partial void Onfactura_idChanged();
    #endregion
		
		public Tbl_factura()
		{
			this._Tbl_DetalleFactura = new EntitySet<Tbl_DetalleFactura>(new Action<Tbl_DetalleFactura>(this.attach_Tbl_DetalleFactura), new Action<Tbl_DetalleFactura>(this.detach_Tbl_DetalleFactura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factura_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int factura_id
		{
			get
			{
				return this._factura_id;
			}
			set
			{
				if ((this._factura_id != value))
				{
					this.Onfactura_idChanging(value);
					this.SendPropertyChanging();
					this._factura_id = value;
					this.SendPropertyChanged("factura_id");
					this.Onfactura_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_factura_Tbl_DetalleFactura", Storage="_Tbl_DetalleFactura", ThisKey="factura_id", OtherKey="factura_id")]
		public EntitySet<Tbl_DetalleFactura> Tbl_DetalleFactura
		{
			get
			{
				return this._Tbl_DetalleFactura;
			}
			set
			{
				this._Tbl_DetalleFactura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_DetalleFactura(Tbl_DetalleFactura entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_factura = this;
		}
		
		private void detach_Tbl_DetalleFactura(Tbl_DetalleFactura entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_factura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_producto")]
	public partial class Tbl_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prod_id;
		
		private string _prod_codigo;
		
		private string _prod_nombre;
		
		private double _prod_precio;
		
		private int _prod_stock;
		
		private System.Nullable<int> _sabor_id;
		
		private System.Data.Linq.Binary _prod_imagen;
		
		private EntitySet<Tbl_DetalleFactura> _Tbl_DetalleFactura;
		
		private EntityRef<Tbl_sabor> _Tbl_sabor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprod_idChanging(int value);
    partial void Onprod_idChanged();
    partial void Onprod_codigoChanging(string value);
    partial void Onprod_codigoChanged();
    partial void Onprod_nombreChanging(string value);
    partial void Onprod_nombreChanged();
    partial void Onprod_precioChanging(double value);
    partial void Onprod_precioChanged();
    partial void Onprod_stockChanging(int value);
    partial void Onprod_stockChanged();
    partial void Onsabor_idChanging(System.Nullable<int> value);
    partial void Onsabor_idChanged();
    partial void Onprod_imagenChanging(System.Data.Linq.Binary value);
    partial void Onprod_imagenChanged();
    #endregion
		
		public Tbl_producto()
		{
			this._Tbl_DetalleFactura = new EntitySet<Tbl_DetalleFactura>(new Action<Tbl_DetalleFactura>(this.attach_Tbl_DetalleFactura), new Action<Tbl_DetalleFactura>(this.detach_Tbl_DetalleFactura));
			this._Tbl_sabor = default(EntityRef<Tbl_sabor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int prod_id
		{
			get
			{
				return this._prod_id;
			}
			set
			{
				if ((this._prod_id != value))
				{
					this.Onprod_idChanging(value);
					this.SendPropertyChanging();
					this._prod_id = value;
					this.SendPropertyChanged("prod_id");
					this.Onprod_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_codigo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string prod_codigo
		{
			get
			{
				return this._prod_codigo;
			}
			set
			{
				if ((this._prod_codigo != value))
				{
					this.Onprod_codigoChanging(value);
					this.SendPropertyChanging();
					this._prod_codigo = value;
					this.SendPropertyChanged("prod_codigo");
					this.Onprod_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string prod_nombre
		{
			get
			{
				return this._prod_nombre;
			}
			set
			{
				if ((this._prod_nombre != value))
				{
					this.Onprod_nombreChanging(value);
					this.SendPropertyChanging();
					this._prod_nombre = value;
					this.SendPropertyChanged("prod_nombre");
					this.Onprod_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_precio", DbType="Float NOT NULL")]
		public double prod_precio
		{
			get
			{
				return this._prod_precio;
			}
			set
			{
				if ((this._prod_precio != value))
				{
					this.Onprod_precioChanging(value);
					this.SendPropertyChanging();
					this._prod_precio = value;
					this.SendPropertyChanged("prod_precio");
					this.Onprod_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_stock", DbType="Int NOT NULL")]
		public int prod_stock
		{
			get
			{
				return this._prod_stock;
			}
			set
			{
				if ((this._prod_stock != value))
				{
					this.Onprod_stockChanging(value);
					this.SendPropertyChanging();
					this._prod_stock = value;
					this.SendPropertyChanged("prod_stock");
					this.Onprod_stockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sabor_id", DbType="Int")]
		public System.Nullable<int> sabor_id
		{
			get
			{
				return this._sabor_id;
			}
			set
			{
				if ((this._sabor_id != value))
				{
					if (this._Tbl_sabor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsabor_idChanging(value);
					this.SendPropertyChanging();
					this._sabor_id = value;
					this.SendPropertyChanged("sabor_id");
					this.Onsabor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_imagen", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary prod_imagen
		{
			get
			{
				return this._prod_imagen;
			}
			set
			{
				if ((this._prod_imagen != value))
				{
					this.Onprod_imagenChanging(value);
					this.SendPropertyChanging();
					this._prod_imagen = value;
					this.SendPropertyChanged("prod_imagen");
					this.Onprod_imagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_producto_Tbl_DetalleFactura", Storage="_Tbl_DetalleFactura", ThisKey="prod_id", OtherKey="prod_id")]
		public EntitySet<Tbl_DetalleFactura> Tbl_DetalleFactura
		{
			get
			{
				return this._Tbl_DetalleFactura;
			}
			set
			{
				this._Tbl_DetalleFactura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_sabor_Tbl_producto", Storage="_Tbl_sabor", ThisKey="sabor_id", OtherKey="sabor_id", IsForeignKey=true)]
		public Tbl_sabor Tbl_sabor
		{
			get
			{
				return this._Tbl_sabor.Entity;
			}
			set
			{
				Tbl_sabor previousValue = this._Tbl_sabor.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_sabor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_sabor.Entity = null;
						previousValue.Tbl_producto.Remove(this);
					}
					this._Tbl_sabor.Entity = value;
					if ((value != null))
					{
						value.Tbl_producto.Add(this);
						this._sabor_id = value.sabor_id;
					}
					else
					{
						this._sabor_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_sabor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_DetalleFactura(Tbl_DetalleFactura entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_producto = this;
		}
		
		private void detach_Tbl_DetalleFactura(Tbl_DetalleFactura entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_rol")]
	public partial class Tbl_rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _rol_id;
		
		private string _rol_tipo;
		
		private EntitySet<Tbl_usuario> _Tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrol_idChanging(int value);
    partial void Onrol_idChanged();
    partial void Onrol_tipoChanging(string value);
    partial void Onrol_tipoChanged();
    #endregion
		
		public Tbl_rol()
		{
			this._Tbl_usuario = new EntitySet<Tbl_usuario>(new Action<Tbl_usuario>(this.attach_Tbl_usuario), new Action<Tbl_usuario>(this.detach_Tbl_usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_tipo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string rol_tipo
		{
			get
			{
				return this._rol_tipo;
			}
			set
			{
				if ((this._rol_tipo != value))
				{
					this.Onrol_tipoChanging(value);
					this.SendPropertyChanging();
					this._rol_tipo = value;
					this.SendPropertyChanged("rol_tipo");
					this.Onrol_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_rol_Tbl_usuario", Storage="_Tbl_usuario", ThisKey="rol_id", OtherKey="roles_id")]
		public EntitySet<Tbl_usuario> Tbl_usuario
		{
			get
			{
				return this._Tbl_usuario;
			}
			set
			{
				this._Tbl_usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_usuario(Tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_rol = this;
		}
		
		private void detach_Tbl_usuario(Tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_sabor")]
	public partial class Tbl_sabor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sabor_id;
		
		private string _sabor_des;
		
		private EntitySet<Tbl_producto> _Tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsabor_idChanging(int value);
    partial void Onsabor_idChanged();
    partial void Onsabor_desChanging(string value);
    partial void Onsabor_desChanged();
    #endregion
		
		public Tbl_sabor()
		{
			this._Tbl_producto = new EntitySet<Tbl_producto>(new Action<Tbl_producto>(this.attach_Tbl_producto), new Action<Tbl_producto>(this.detach_Tbl_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sabor_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sabor_id
		{
			get
			{
				return this._sabor_id;
			}
			set
			{
				if ((this._sabor_id != value))
				{
					this.Onsabor_idChanging(value);
					this.SendPropertyChanging();
					this._sabor_id = value;
					this.SendPropertyChanged("sabor_id");
					this.Onsabor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sabor_des", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string sabor_des
		{
			get
			{
				return this._sabor_des;
			}
			set
			{
				if ((this._sabor_des != value))
				{
					this.Onsabor_desChanging(value);
					this.SendPropertyChanging();
					this._sabor_des = value;
					this.SendPropertyChanged("sabor_des");
					this.Onsabor_desChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_sabor_Tbl_producto", Storage="_Tbl_producto", ThisKey="sabor_id", OtherKey="sabor_id")]
		public EntitySet<Tbl_producto> Tbl_producto
		{
			get
			{
				return this._Tbl_producto;
			}
			set
			{
				this._Tbl_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_producto(Tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_sabor = this;
		}
		
		private void detach_Tbl_producto(Tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_sabor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_tipo_pago")]
	public partial class Tbl_tipo_pago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tipo_pago_id;
		
		private string _tipo_pago_des;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontipo_pago_idChanging(int value);
    partial void Ontipo_pago_idChanged();
    partial void Ontipo_pago_desChanging(string value);
    partial void Ontipo_pago_desChanged();
    #endregion
		
		public Tbl_tipo_pago()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_pago_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tipo_pago_id
		{
			get
			{
				return this._tipo_pago_id;
			}
			set
			{
				if ((this._tipo_pago_id != value))
				{
					this.Ontipo_pago_idChanging(value);
					this.SendPropertyChanging();
					this._tipo_pago_id = value;
					this.SendPropertyChanged("tipo_pago_id");
					this.Ontipo_pago_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_pago_des", DbType="NChar(40)")]
		public string tipo_pago_des
		{
			get
			{
				return this._tipo_pago_des;
			}
			set
			{
				if ((this._tipo_pago_des != value))
				{
					this.Ontipo_pago_desChanging(value);
					this.SendPropertyChanging();
					this._tipo_pago_des = value;
					this.SendPropertyChanged("tipo_pago_des");
					this.Ontipo_pago_desChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_usuario")]
	public partial class Tbl_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_usu;
		
		private string _usu_nombre;
		
		private string _usu_apellido;
		
		private string _usu_pass;
		
		private string _usu_cedula;
		
		private string _usu_correo;
		
		private string _usu_dire;
		
		private string _usu_celular;
		
		private string _usu_estado;
		
		private int _roles_id;
		
		private EntityRef<Tbl_rol> _Tbl_rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_usuChanging(string value);
    partial void Onusu_usuChanged();
    partial void Onusu_nombreChanging(string value);
    partial void Onusu_nombreChanged();
    partial void Onusu_apellidoChanging(string value);
    partial void Onusu_apellidoChanged();
    partial void Onusu_passChanging(string value);
    partial void Onusu_passChanged();
    partial void Onusu_cedulaChanging(string value);
    partial void Onusu_cedulaChanged();
    partial void Onusu_correoChanging(string value);
    partial void Onusu_correoChanged();
    partial void Onusu_direChanging(string value);
    partial void Onusu_direChanged();
    partial void Onusu_celularChanging(string value);
    partial void Onusu_celularChanged();
    partial void Onusu_estadoChanging(string value);
    partial void Onusu_estadoChanged();
    partial void Onroles_idChanging(int value);
    partial void Onroles_idChanged();
    #endregion
		
		public Tbl_usuario()
		{
			this._Tbl_rol = default(EntityRef<Tbl_rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_usu", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string usu_usu
		{
			get
			{
				return this._usu_usu;
			}
			set
			{
				if ((this._usu_usu != value))
				{
					this.Onusu_usuChanging(value);
					this.SendPropertyChanging();
					this._usu_usu = value;
					this.SendPropertyChanged("usu_usu");
					this.Onusu_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string usu_nombre
		{
			get
			{
				return this._usu_nombre;
			}
			set
			{
				if ((this._usu_nombre != value))
				{
					this.Onusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._usu_nombre = value;
					this.SendPropertyChanged("usu_nombre");
					this.Onusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string usu_apellido
		{
			get
			{
				return this._usu_apellido;
			}
			set
			{
				if ((this._usu_apellido != value))
				{
					this.Onusu_apellidoChanging(value);
					this.SendPropertyChanging();
					this._usu_apellido = value;
					this.SendPropertyChanged("usu_apellido");
					this.Onusu_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_pass", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string usu_pass
		{
			get
			{
				return this._usu_pass;
			}
			set
			{
				if ((this._usu_pass != value))
				{
					this.Onusu_passChanging(value);
					this.SendPropertyChanging();
					this._usu_pass = value;
					this.SendPropertyChanged("usu_pass");
					this.Onusu_passChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string usu_cedula
		{
			get
			{
				return this._usu_cedula;
			}
			set
			{
				if ((this._usu_cedula != value))
				{
					this.Onusu_cedulaChanging(value);
					this.SendPropertyChanging();
					this._usu_cedula = value;
					this.SendPropertyChanged("usu_cedula");
					this.Onusu_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usu_correo
		{
			get
			{
				return this._usu_correo;
			}
			set
			{
				if ((this._usu_correo != value))
				{
					this.Onusu_correoChanging(value);
					this.SendPropertyChanging();
					this._usu_correo = value;
					this.SendPropertyChanged("usu_correo");
					this.Onusu_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_dire", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string usu_dire
		{
			get
			{
				return this._usu_dire;
			}
			set
			{
				if ((this._usu_dire != value))
				{
					this.Onusu_direChanging(value);
					this.SendPropertyChanging();
					this._usu_dire = value;
					this.SendPropertyChanged("usu_dire");
					this.Onusu_direChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_celular", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string usu_celular
		{
			get
			{
				return this._usu_celular;
			}
			set
			{
				if ((this._usu_celular != value))
				{
					this.Onusu_celularChanging(value);
					this.SendPropertyChanging();
					this._usu_celular = value;
					this.SendPropertyChanged("usu_celular");
					this.Onusu_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_estado", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string usu_estado
		{
			get
			{
				return this._usu_estado;
			}
			set
			{
				if ((this._usu_estado != value))
				{
					this.Onusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._usu_estado = value;
					this.SendPropertyChanged("usu_estado");
					this.Onusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roles_id", DbType="Int NOT NULL")]
		public int roles_id
		{
			get
			{
				return this._roles_id;
			}
			set
			{
				if ((this._roles_id != value))
				{
					if (this._Tbl_rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onroles_idChanging(value);
					this.SendPropertyChanging();
					this._roles_id = value;
					this.SendPropertyChanged("roles_id");
					this.Onroles_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_rol_Tbl_usuario", Storage="_Tbl_rol", ThisKey="roles_id", OtherKey="rol_id", IsForeignKey=true)]
		public Tbl_rol Tbl_rol
		{
			get
			{
				return this._Tbl_rol.Entity;
			}
			set
			{
				Tbl_rol previousValue = this._Tbl_rol.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_rol.Entity = null;
						previousValue.Tbl_usuario.Remove(this);
					}
					this._Tbl_rol.Entity = value;
					if ((value != null))
					{
						value.Tbl_usuario.Add(this);
						this._roles_id = value.rol_id;
					}
					else
					{
						this._roles_id = default(int);
					}
					this.SendPropertyChanged("Tbl_rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
