<?xml version="1.0" encoding="utf-8"?><Database Name="Heladeria_CA" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CHRISTIAN;Initial Catalog=Heladeria_CA;Integrated Security=True" SettingsObjectName="HELADERIA_CA.Properties.Settings" SettingsPropertyName="Heladeria_CAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tbl_factura" Member="Tbl_factura">
    <Type Name="Tbl_factura">
      <Column Name="fac_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fac_cedula" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="fac_nombres" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fac_correo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="fac_numero" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="fac_direccion" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="fac_prod1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fac_saborp1" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="fac_prod2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fac_saborp2" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="fac_prod3" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fac_saborp3" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="fac_prod4" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fac_prod5" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fac_prod6" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fac_prod7" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fac_prod8" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fac_prod9" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fac_subtotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="fac_iva" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="fac_total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_producto" Member="Tbl_producto">
    <Type Name="Tbl_producto">
      <Column Name="prod_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="prod_codigo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="prod_nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="prod_precio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_rol" Member="Tbl_rol">
    <Type Name="Tbl_rol">
      <Column Name="rol_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rol_tipo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Tbl_rol_Tbl_usuario" Member="Tbl_usuario" ThisKey="rol_id" OtherKey="roles_id" Type="Tbl_usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_usuario" Member="Tbl_usuario">
    <Type Name="Tbl_usuario">
      <Column Name="usu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usu_usu" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="usu_nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="usu_apellido" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="usu_pass" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="usu_cedula" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="usu_correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="usu_dire" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="usu_celular" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="usu_estado" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="roles_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tbl_rol_Tbl_usuario" Member="Tbl_rol" ThisKey="roles_id" OtherKey="rol_id" Type="Tbl_rol" IsForeignKey="true" />
    </Type>
  </Table>
</Database>